Lab 3: Numpy

Nidhi Mehta

0827CI191039

In [3]:
import numpy as np

In [4]:
arr = np.array([[[1, 2, 3, 9], [3, 4, 5, 10], [6, 7, 8, 10]], [[1, 2, 3, 10], [3, 4, 5, 10], [6, 7, 8, 10]], [[1, 2, 3, 10], [3, 4, 5, 10], [6, 7, 8, 10]]])
print(arr)    #prints arr
print(arr.shape)  #prints (x, y, z) dimensions
print(arr.ndim)   #prints dimension of matrix

[[[ 1  2  3  9]
  [ 3  4  5 10]
  [ 6  7  8 10]]

 [[ 1  2  3 10]
  [ 3  4  5 10]
  [ 6  7  8 10]]

 [[ 1  2  3 10]
  [ 3  4  5 10]
  [ 6  7  8 10]]]
(3, 3, 4)
3


In [6]:
arr = np.array([[[1, 2, 3, 9], [3, 4, 5, 10], [6, 7, 8, 10]], [[1, 2, 3, 10], [3, 4, 5, 10], [6, 7, 8, 10]], [[1, 2, 3, 10], [3, 4, 5, 10], [6, 7, 8, 10]]])
arr.resize(3, 9)   #resize changes original array
print(arr)    
print(arr.shape)

[[ 1  2  3  9  3  4  5 10  6]
 [ 7  8 10  1  2  3 10  3  4]
 [ 5 10  6  7  8 10  1  2  3]]
(3, 9)


In [8]:
arr = np.array([[[1, 2, 3, 9], [3, 4, 5, 10], [6, 7, 8, 10]], [[1, 2, 3, 10], [3, 4, 5, 10], [6, 7, 8, 10]], [[1, 2, 3, 10], [3, 4, 5, 10], [6, 7, 8, 10]]])
print(arr.reshape(9, 4)) #reshape does not change original array
print(arr.shape)

[[ 1  2  3  9]
 [ 3  4  5 10]
 [ 6  7  8 10]
 [ 1  2  3 10]
 [ 3  4  5 10]
 [ 6  7  8 10]
 [ 1  2  3 10]
 [ 3  4  5 10]
 [ 6  7  8 10]]
(3, 3, 4)


In [9]:
emp = np.empty((2, 3), dtype = np.int64)  # empty array of dimensions 2 x 3
print(emp) #garbage values

[[94738393116752              0              0]
 [             0              0              0]]


In [10]:
r = np.random.random((2,2))
print(r)

[[0.41389496 0.10261994]
 [0.64121571 0.52151583]]


In [11]:
x = np.ones(3, dtype = np.int32)
y = np.linspace(0, 3, 4)
print(x)
print(y)
print(x.sum(), y.min(), y.max())

[1 1 1]
[0. 1. 2. 3.]
3 0.0 3.0


In [12]:
f = np.array([[6, 9], [8, 4], [5, 10]])
f = f.flatten()
print(f)

[ 6  9  8  4  5 10]
